USE Rapizz;
-- Table drop script --
DROP TABLE IF EXISTS Compose;
DROP TABLE IF EXISTS Command;
DROP TABLE IF EXISTS Vehicle;
DROP TABLE IF EXISTS Livreur;
DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Ingredient;
DROP TABLE IF EXISTS Pizza;